# -*- coding: utf-8 -*-
"""Uni-V3 Math.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIir7h_RbMRDurF-dJbu3vbyxW-4VwKr

# Tick To Price WBTC/USDT
"""

# [ slot0 method Response ]
#   sqrtPriceX96   uint160 :  2319892999208886007539301351424
#   tick   int24 :  67542
#   observationIndex   uint16 :  141
#   observationCardinality   uint16 :  360
#   observationCardinalityNext   uint16 :  360
#   feeProtocol   uint8 :  0
#   unlocked   bool :  true

# WBTC/USDT POOL (Arbitrum ):  https://arbiscan.io/address/0x5969EFddE3cF5C0D9a88aE51E47d721096A97203#readContract
# Decimals     WBTC=8     USDT=6
# p = y/x price of y in terms of x (WBTC 1e8 in terms of USDT 1e6)


tick = 67542
price = 1.0001 ** float(tick)
print(f"1 WBTC = {price * 1e8 / 1e6} USDT")

"""# SqrtPricex96 To Price WBTC/USDT

"""

# [ slot0 method Response ]
#   sqrtPriceX96   uint160 :  2319892999208886007539301351424
#   tick   int24 :  67542
#   observationIndex   uint16 :  141
#   observationCardinality   uint16 :  360
#   observationCardinalityNext   uint16 :  360
#   feeProtocol   uint8 :  0
#   unlocked   bool :  true

# WBTC/USDT POOL (Arbitrum ):  https://arbiscan.io/address/0x5969EFddE3cF5C0D9a88aE51E47d721096A97203#readContract
# Decimals     WBTC=8     USDT=6
# p = y/x price of y in terms of x (WBTC 1e8 in terms of USDT 1e6)


sqrtPriceX96 = 2319892999208886007539301351424
Q96 = 2 ** 96
price = (sqrtPriceX96 / Q96) ** 2
print(f"1 WBTC = {price * 1e8 / 1e6} USDT")

"""# Tick to Price WETH/GMX"""

# [ slot0 method Response ]
#   sqrtPriceX96   uint160 :  1481537414666458718730651116072
#   tick   int24 :  58573
#   observationIndex   uint16 :  6062
#   observationCardinality   uint16 :  7200
#   observationCardinalityNext   uint16 :  7200
#   feeProtocol   uint8 :  0
#   unlocked   bool :  true

# WETH/GMX POOL (Arbitrum ):  https://arbiscan.io/address/0x5969EFddE3cF5C0D9a88aE51E47d721096A97203#readContract
# Decimals     WETH=8     GMX=6
# p = y/x price of y in terms of x (WETH 1e8 in terms of GMX 1e6)


tick = 58573
price = 1.0001 ** float(tick)
print(f"1 WETH = {price * 1e18/1e18} GMX")

"""# SqrtPricex96 To Price WETH/GMX"""

# [ slot0 method Response ]
#   sqrtPriceX96   uint160 :  1481537414666458718730651116072
#   tick   int24 :  58573
#   observationIndex   uint16 :  6062
#   observationCardinality   uint16 :  7200
#   observationCardinalityNext   uint16 :  7200
#   feeProtocol   uint8 :  0
#   unlocked   bool :  true

# WETH/GMX POOL (Arbitrum ):  https://arbiscan.io/address/0x5969EFddE3cF5C0D9a88aE51E47d721096A97203#readContract
# Decimals     WETH=8     GMX=6
# p = y/x price of y in terms of x (WETH 1e8 in terms of GMX 1e6)


sqrtPriceX96 = 1481537414666458718730651116072
Q96 = 2 ** 96
price = (sqrtPriceX96 / Q96) ** 2
print(f"1 WETH = {price * 1e18/1e18} GMX")